[Improvement] - Readme and Linter
betrybe/sd-0x-crush-manager pull request #7
Opened 2021-02-11 14:19 UTC by LizzardMedeiros

**Criei um PR novo, pois o outro estava com problemas demais. Refatorei praticamente 80% do projeto**

Correção dos _linters_ e atualização do _README_

[PR antigo](https://github.com/betrybe/sd-0x-crush-manager/pull/4) para consultar os CRs

- [x] Checks ESLint
- [x] Testes internos
- [ ] [Repositório Tests](https://github.com/betrybe/sd-0x-crush-manager-tests/pull/3) (precisa mergear)
- [ ] [Rubrica](https://github.com/betrybe/sd-0x-crush-manager-rubric)

Closes https://github.com/betrybe/course/issues/2713

[Sprint](https://github.com/betrybe/course/issues/2543)

2021-02-12 11:23 UTC, phelipe-ohlsen approved these changes

2021-02-25 12:56 UTC, LucasSGomide requested changes
FIcou show de bola Lizz !

2021-02-25 12:56 UTC, LucasSGomide commented on README.md
> +4. Ao utilizar de testes locais com `npm run test`, o servidor deverá ser iniciado com `npm run debug` para evitar possíveis erros.
```suggestion
4. Ao realizar testes locais com `npm run test`, o servidor deverá ser iniciado com `npm run debug` para evitar possíveis erros.
```

2021-02-25 12:56 UTC, LucasSGomide commented on README.md
> +5. Caso os testes falhem seu arquivo `crush.json` não será restaurado, para isso utilize `npm run restore`.
```suggestion
5. Após o teste local seu arquivo `crush.json` ficará vazio. Para que ele retorne à configuração inicial utilize `npm run restore`.
```

@LizzardMedeiros Não sei se essa alteração se aplica, não lembro se ele limpa o arquivo **apenas** quando os testes falham, se for, acho que seja válido dizer algo como:

Caso os testes falhem seu arquivo `crush.json` ficará vazio. Para que ele retorne à configuração inicial, utilize `npm run restore`.

Na minha opinião fica mais claro, o que acha ? :thinking:

2021-02-25 13:23 UTC, LucasSGomide approved these changes

2021-02-25 13:51 UTC, brunobatista25 requested changes

2021-02-25 13:51 UTC, brunobatista25 commented on .github/workflows/main.yml
> +  evaluator_job:
da so um espaço entre os jobs

2021-02-25 13:51 UTC, brunobatista25 commented on .github/workflows/main.yml
>  jobs:
da so um espaço entre os jobs

2021-02-25 13:51 UTC, brunobatista25 commented on package.json
>      "lint": "eslint --no-inline-config --no-error-on-unmatched-pattern -c .eslintrc.json ."
```suggestion
     "lint": "eslint --no-inline-config --no-error-on-unmatched-pattern -c .eslintrc.json . --ext .js,.jsx"
```

2021-03-04 18:50 UTC, roziscoding approved these changes

2021-03-05 11:16 UTC, merged