[KR 3C - PENTE FINO] Crush Manager -> Talker Manager
betrybe/sd-0x-crush-manager pull request #8
Opened 2021-02-25 16:31 UTC by roziscoding

2021-03-03 21:06 UTC, albertosca requested changes
Tem alguns componentes dos READMEs que estamos puxando como padrão que não estão aqui. Os seguintes:
1. Em cada requisito, no README, transcrever o descritor dos `it`s numa seção [O que será verificado:](https://github.com/betrybe/sd-0x-project-movie-card-library-crud/pull/23/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R279)
2. Uma separação no índice definindo quais são os `Requisitos obrigatórios`
3. Seções instruindo a rodar linters e testes. [Linhas 23 a 25](https://github.com/betrybe/sd-0x-project-movie-card-library-crud/pull/23/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R23). Isso mata a seção `Como desenvolver`
4. O `Depois de terminar o desenvolvimento` vai pro final.

2021-03-03 21:06 UTC, albertosca commented on tests/searchTalker.test.js
> +  it('Será validade que o endpoit retonar um array com todos as pessoas palestrantes caso o param seja vazio', async () => {
```suggestion
  it('Será validado que o endpoint retonará um array com todos as pessoas palestrantes caso param seja vazio', async () => {
```

2021-04-04 14:01 UTC, gabrielrufino commented
Bom dia, gente!
Amanhã vamos rodar esse projeto na T7. Devemos nos preocupar com esse PR?

Me desculpem por estar comentando em um domingo hehe

2021-05-04 22:56 UTC, vinicius-vasconcelos requested changes
@roziscoding só observar a questão do `project` e sem `project` e os nomes dos repositórios, de crush para talker, ver se faz sentido :smile:

2021-05-12 12:35 UTC, roziscoding commented on .github/workflows/main.yml
> +          repository-test-name: 'betrybe/sd-0x-talker-manager-tests'
Precisamos renomear. Vou renomear todos uma vez que esses PRs forem mergeados

2021-05-12 12:36 UTC, roziscoding commented on README.md
> +  - `cd sd-0x-project-talker-manager`
Até onde eu sei é pra ter project em tudo, a não ser que tenha mudado.
@antoniosb temos algo definido sobre?

2021-05-12 12:37 UTC, roziscoding commented on README.md
>      - Caso o campo não seja informa, esteja vazio ou então alguma de suas chaves não tenham sido informadas retorne `status 400`, com o seguinte corpo:
```suggestion
    - Caso o campo não seja informado, esteja vazio ou então alguma de suas chaves não tenham sido informadas retorne `status 400`, com o seguinte corpo:
```

2021-05-12 12:38 UTC, roziscoding commented on README.md
>      }
O que a gente mostra aqui é só exemplo pra pessoa saber o formato do JSON. Não deve interferir nos testes. Pros testes, o que importa é o conteúdo do `talkers.json`

2021-05-12 12:39 UTC, roziscoding commented on package.json
> +  "name": "sd-0x-project-talker-manager",
Vamos manter **com** o project

2021-05-14 18:34 UTC, vinicius-vasconcelos approved these changes

2021-05-17 18:57 UTC, merged